languageCode = "en"
languageName = "English"
weight = 1
title = "THΞ SHΞLL"
#title = '~~~[ THE SHELL ]~~~

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/ghost.png" # This is the blog's picture.
  #description = "A personal Blog."

[params.author]
  name = "YΛNGΛ"
  email = "resuper@protonmail.com"
  image = "img/authors_logo_merged_gif.gif" # This is the author's picture.
  headline = "A personal blog."
  bio = "Memento Mori."
  links = [
    
    { linkedin = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
    { envelope = "https://twitter.com/burufugu" },
    { x-twitter = "https://twitter.com/burufugu" },

  ]